name: polygeek_lints
description: My lints to share across projects.
repository: https://github.com/polyGeek/polygeek_lints
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # lints: ^1.0.0
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
